### ISSUE TITLE
getssl is run every puppet run

### ISSUE THREAD

**Issue by nickcmaynard** [dthielking/puppet_getssl#3]
getssl is run per-domain every time puppet runs.  I'm not sure that's what was intended.  
I'd expect this only to happen if the config file changes - in this case, the notify there will run it.  

I *think* the appropriate way to achieve this is to add `refreshonly => true` to the getssl exec spec (https://github.com/dthielking/puppet_getssl/blob/master/manifests/domain.pp#L185-L187) - see https://docs.puppet.com/puppet/3.8/types/exec.html

**Comment by bitfoo1** [comment]
I think your pull request fixes this issue. So I will close it after merging it. Thank you for your PR!

**Comment by nickcmaynard** [comment]
Hurrah!  Thanks!
