### ISSUE TITLE
Reload command does not default to global reload command

### ISSUE THREAD

**Issue by davidc** [dthielking/puppet_getssl#8]
If the reload command is omitted from the domain, it does not default to the global command as documented, because an empty RELOAD_CMD is still emitted into the domain configuration file.

Fix is simple:

```
--- domain_getssl.cfg.epp       2018-03-24 14:30:59.900862860 +0000
+++ domain_getssl.cfg.epp.orig      2017-01-04 12:57:31.000000000 +0000
@@ -45,10 +45,8 @@
 DOMAIN_PEM_LOCATION="<%= $doamin_pem_location -%>"
 <% } -%>

-<% if $domain_reload_command { -%>
 # The command needed to reload apache / nginx or whatever you use
 RELOAD_CMD="<%= $domain_reload_command -%>"
-<% } -%>
 # The time period within which you want to allow renewal of a certificate
 #  this prevents hitting some of the rate limits.
 RENEW_ALLOW=<%= $domain_renew_allow %>
```

**Comment by bitfoo1** [comment]
Hello @davidc, unfortunately I'm currently not able to test your PR. I'm not involved in puppet anymore. I will merge your PR but do not publish a new version on puppet forge.
Hope that helps.
